# Defaults for a Pokemon Alola Adventure server. Change freely.
motd=§eAlola! §bA Pokémon Sun & Moon adventure §7(Cobblemon)
allow-flight=true
difficulty=normal
spawn-protection=0
view-distance=10
simulation-distance=8
max-tick-time=120000
enable-command-block=false
